import "server-only";

import {
  DocumentDefinitionStatus,
  DocumentDeliveryMode,
  DocumentFieldType,
  DocumentPolicySeverity,
  DocumentPolicyType,
  DocumentSequenceScope,
  DocumentTemplateOwnership,
  DocumentTemplateVersionStatus,
  DocumentType,
  DocumentWorkflowApprovalMode,
  DocumentWorkflowStepType,
  Prisma,
} from "@prisma/client";
import { platformPrisma } from "@/lib/db";
import { CERTIFIED_TEMPLATE_TENANT_ID } from "@/lib/services/document-template-ownership";
import type { DocumentTemplateDefinition } from "@/lib/services/document-template-builder";
import type { DocumentExecutionContext } from "@/lib/services/document-runtime-context";
import { requireDocumentPermission } from "@/lib/services/document-runtime-context";
import { writeDocumentAudit } from "@/lib/services/document-runtime-audit";

export const CERTIFICATE_OF_RESIDENCY_CODE = "CERTIFICATE_OF_RESIDENCY";
export const CERTIFICATE_OF_RESIDENCY_CERTIFIED_KEY = "HOAHUB:CERTIFICATE_OF_RESIDENCY";
export const CERTIFICATE_OF_RESIDENCY_WORKFLOW_CODE = "COR_STANDARD_APPROVAL";

export function certificateOfResidencyTemplateDefinition(): DocumentTemplateDefinition {
  const definition: DocumentTemplateDefinition = {
    schemaVersion: 2,
    page: {
      format: "A4",
      orientation: "portrait",
      marginPreset: "custom",
      margins: { top: 20, right: 20, bottom: 20, left: 20 },
      headerDistance: 10,
      footerDistance: 10,
      columns: { count: 1, gap: 10 },
      border: { enabled: true, style: "solid", width: 1, color: "#166534" },
      backgroundColor: "#ffffff",
      watermark: { enabled: false, text: "", opacity: 0.08 },
      canvas: { gridSize: 5, snapToGrid: true, showGrid: true },
    },
    sections: {
      header: [
        block("cor-logo", "logo", "header", 10, "{{tenant.logo}}", false, { align: "center", width: 72, height: 72 }),
        block("cor-association", "tenantName", "header", 20, "{{tenant.name}}", true, { align: "center", fontFamily: "Times New Roman", fontSize: 17, fontWeight: "bold" }),
        block("cor-address", "address", "header", 30, "{{tenant.address}}", true, { align: "center", fontFamily: "Arial", fontSize: 10 }),
        block("cor-sec", "text", "header", 40, "SEC Registration: {{tenant.secRegistration}}", false, { align: "center", fontFamily: "Arial", fontSize: 9 }),
        block("cor-tin", "text", "header", 50, "TIN: {{tenant.tin}}", false, { align: "center", fontFamily: "Arial", fontSize: 9 }),
        block("cor-contact", "text", "header", 60, "{{tenant.contactNumber}} | {{tenant.email}}", false, { align: "center", fontFamily: "Arial", fontSize: 9 }),
        block("cor-divider", "horizontalLine", "header", 70, "", false, { margin: 10 }),
      ],
      body: [
        block("cor-title", "documentTitle", "body", 10, "CERTIFICATE OF RESIDENCY", true, { align: "center", fontFamily: "Times New Roman", fontSize: 20, fontWeight: "bold", paragraphSpacing: 18 }),
        block("cor-body", "bodyText", "body", 20, "This is to certify that {{subject.fullName}} is a bona fide resident of {{property.address}}, located within {{tenant.name}}.", true, { align: "justify", fontFamily: "Times New Roman", fontSize: 12, lineHeight: 1.7, paragraphSpacing: 12 }),
        block("cor-property", "propertyInfo", "body", 30, "Property identification: Block {{property.block}}, Lot {{property.lot}}.", true, { align: "justify", fontFamily: "Times New Roman", fontSize: 12, lineHeight: 1.6 }),
        block("cor-status", "subjectInfo", "body", 40, "Residency status: {{subject.status}}.", false, { align: "justify", fontFamily: "Times New Roman", fontSize: 12 }),
        block("cor-residency-date", "subjectInfo", "body", 50, "Residency start date: {{subject.residencyStartDate}}.", false, { align: "justify", fontFamily: "Times New Roman", fontSize: 12 }),
        block("cor-purpose", "purpose", "body", 60, "This certification is issued upon the request of the above-named resident for {{request.purpose}}.", true, { align: "justify", fontFamily: "Times New Roman", fontSize: 12, lineHeight: 1.7, paragraphSpacing: 12 }),
        block("cor-issuance", "issueDate", "body", 70, "Issued on {{document.issueDate}} at {{document.issuePlace}}. Official document number: {{document.number}}.", true, { align: "justify", fontFamily: "Times New Roman", fontSize: 12, lineHeight: 1.6, paragraphSpacing: 20 }),
        block("cor-signature-space", "spacer", "body", 80, "", false, { height: 36 }),
        block("cor-signatory", "signatory", "body", 90, "{{signatory.name}}\n{{signatory.position}}\nAuthorized HOA Signatory", true, { align: "right", fontFamily: "Times New Roman", fontSize: 12, fontWeight: "bold" }),
        block("cor-qr", "qrVerification", "body", 100, "Scan to verify {{document.number}}", true, { align: "left", width: 112, height: 112, margin: 12 }),
      ],
      footer: [
        block("cor-footer", "footer", "footer", 10, "This document was electronically generated by HOAHub and may be verified using the QR code shown above.", true, { align: "center", fontFamily: "Arial", fontSize: 8, textColor: "#475569" }),
      ],
    },
    blocks: [],
    meta: {
      editor: "professional-document-editor",
      revisionNote: "HOAHub Certificate of Residency certified reference template v1.0.",
      requiresSignatory: true,
    },
  };
  definition.blocks = [...definition.sections.header, ...definition.sections.body, ...definition.sections.footer];
  return definition;
}

export async function ensureCertifiedCertificateOfResidencyTemplate() {
  const host = await platformPrisma.tenant.findUnique({ where: { id: CERTIFIED_TEMPLATE_TENANT_ID }, select: { id: true } });
  if (!host) throw new Error("The configured certified-template host tenant does not exist.");

  return platformPrisma.$transaction(async (tx) => {
    let definition = await tx.documentDefinition.findFirst({
      where: { tenantId: host.id, code: CERTIFICATE_OF_RESIDENCY_CODE },
      select: { id: true },
    });
    if (!definition) {
      definition = await tx.documentDefinition.create({
        data: {
          tenantId: host.id,
          code: CERTIFICATE_OF_RESIDENCY_CODE,
          displayName: "Certificate of Residency",
          description: "Official HOA certification of a verified resident and property relationship.",
          category: "Official HOA Certification",
          systemKey: CERTIFICATE_OF_RESIDENCY_CODE,
          legacyType: DocumentType.CERTIFICATE_OF_RESIDENCY,
          status: DocumentDefinitionStatus.INACTIVE,
          active: false,
          walkInEnabled: true,
          qrEnabled: true,
          releaseRequired: true,
          numberingFormat: "COR-{YYYY}-{SEQUENCE:6}",
        },
        select: { id: true },
      });
    }

    const existing = await tx.documentTemplateSet.findFirst({
      where: { tenantId: host.id, certifiedKey: CERTIFICATE_OF_RESIDENCY_CERTIFIED_KEY, ownershipType: DocumentTemplateOwnership.CERTIFIED },
      include: { versions: { where: { status: DocumentTemplateVersionStatus.PUBLISHED }, orderBy: { version: "desc" }, take: 1 } },
    });
    if (existing?.versions[0]) return { created: false, set: existing, version: existing.versions[0] };

    const set = existing ?? await tx.documentTemplateSet.create({
      data: {
        tenantId: host.id,
        definitionId: definition.id,
        name: "HOAHub Certified Certificate of Residency",
        description: "Read-only certified reference template. Tenants customize cloned copies only.",
        active: true,
        ownershipType: DocumentTemplateOwnership.CERTIFIED,
        certifiedKey: CERTIFICATE_OF_RESIDENCY_CERTIFIED_KEY,
        upgradeCompatible: true,
        restorable: true,
        editable: false,
      },
    });
    const version = await tx.documentTemplateVersion.create({
      data: {
        tenantId: host.id,
        templateSetId: set.id,
        version: 1,
        status: DocumentTemplateVersionStatus.PUBLISHED,
        ownershipType: DocumentTemplateOwnership.CERTIFIED,
        schemaVersion: 2,
        definitionJson: asJson(certificateOfResidencyTemplateDefinition()),
        previewMetadata: asJson({ certifiedKey: CERTIFICATE_OF_RESIDENCY_CERTIFIED_KEY, release: "1.0" }),
        publishedAt: new Date(),
        upgradeCompatible: true,
        restorable: true,
      },
    });
    await tx.auditLog.create({
      data: {
        tenantId: host.id,
        module: "DOCUMENTS",
        action: "SEED_CERTIFIED_CERTIFICATE_TEMPLATE",
        entityType: "DocumentTemplateVersion",
        entityId: version.id,
        metadata: asJson({ certifiedKey: CERTIFICATE_OF_RESIDENCY_CERTIFIED_KEY, version: 1 }),
      },
    });
    return { created: true, set: { ...set, versions: [version] }, version };
  });
}

export async function provisionCertificateOfResidencyForTenant(context: DocumentExecutionContext) {
  requireDocumentPermission(context, "MANAGE_DEFINITIONS");
  const actor = await platformPrisma.user.findFirst({
    where: { id: context.authenticatedUserId, tenantId: context.tenantId, active: true },
    select: { id: true },
  });
  if (!actor) throw new Error("Provisioning actor does not belong to the target tenant.");
  const certified = await ensureCertifiedCertificateOfResidencyTemplate();

  return platformPrisma.$transaction(async (tx) => {
    let definition = await tx.documentDefinition.findFirst({
      where: { tenantId: context.tenantId, code: CERTIFICATE_OF_RESIDENCY_CODE },
      include: { assignedTemplateVersion: { include: { templateSet: true } } },
    });
    const createdDefinition = !definition;
    if (!definition) {
      definition = await tx.documentDefinition.create({
        data: {
          tenantId: context.tenantId,
          code: CERTIFICATE_OF_RESIDENCY_CODE,
          displayName: "Certificate of Residency",
          description: "Certifies that a named homeowner or authorized resident resides at a property within the association.",
          category: "Official HOA Certification",
          status: DocumentDefinitionStatus.ACTIVE,
          active: true,
          systemKey: CERTIFICATE_OF_RESIDENCY_CODE,
          legacyType: DocumentType.CERTIFICATE_OF_RESIDENCY,
          deliveryMode: DocumentDeliveryMode.APPROVAL_REQUIRED,
          approvalRequired: true,
          paymentRequired: false,
          allowImmediateDownload: false,
          requiresAdminReview: true,
          releaseRequired: true,
          homeownerDownloadEnabled: true,
          walkInEnabled: true,
          householdMemberEnabled: true,
          allowRegeneration: true,
          feeAmount: new Prisma.Decimal(0),
          numberingFormat: "COR-{YYYY}-{SEQUENCE:6}",
          sequenceScope: DocumentSequenceScope.ANNUAL,
          maxCopies: 1,
          qrEnabled: true,
          createdById: actor.id,
          updatedById: actor.id,
        },
        include: { assignedTemplateVersion: { include: { templateSet: true } } },
      });
    }

    const fields = [
      { key: "purpose", label: "Purpose", fieldType: DocumentFieldType.TEXTAREA, required: true, displayOrder: 10, validation: { minLength: 3, maxLength: 500 } },
      { key: "intendedRecipient", label: "Intended recipient", fieldType: DocumentFieldType.TEXT, required: false, displayOrder: 20, validation: { maxLength: 150 } },
      { key: "remarks", label: "Additional remarks", fieldType: DocumentFieldType.TEXTAREA, required: false, displayOrder: 30, validation: { maxLength: 1000 } },
    ] as const;
    for (const field of fields) {
      await tx.documentDefinitionField.upsert({
        where: { tenantId_definitionId_key: { tenantId: context.tenantId, definitionId: definition.id, key: field.key } },
        create: { tenantId: context.tenantId, definitionId: definition.id, ...field, validation: asJson(field.validation) },
        update: {},
      });
    }

    let workflow = await tx.documentWorkflowDefinition.findFirst({ where: { tenantId: context.tenantId, code: CERTIFICATE_OF_RESIDENCY_WORKFLOW_CODE } });
    if (!workflow) {
      workflow = await tx.documentWorkflowDefinition.create({
        data: {
          tenantId: context.tenantId,
          code: CERTIFICATE_OF_RESIDENCY_WORKFLOW_CODE,
          name: "Certificate of Residency Approval",
          description: "One authorized tenant approval before official issuance.",
          approvalMode: DocumentWorkflowApprovalMode.SEQUENTIAL,
          createdById: actor.id,
          updatedById: actor.id,
        },
      });
      await tx.documentWorkflowStep.create({
        data: {
          tenantId: context.tenantId,
          workflowId: workflow.id,
          stepOrder: 1,
          stepType: DocumentWorkflowStepType.APPROVAL,
          approvalMode: DocumentWorkflowApprovalMode.SEQUENTIAL,
          required: true,
          overrideEligible: true,
          mandatoryOverrideRemarks: true,
          createdById: actor.id,
          updatedById: actor.id,
        },
      });
    }
    if (!definition.workflowDefinitionId) {
      await tx.documentDefinition.update({ where: { id: definition.id }, data: { workflowDefinitionId: workflow.id, version: { increment: 1 }, updatedById: actor.id } });
    }

    const policies = [
      { code: "COR_ACTIVE_RESIDENT", name: "Active resident", type: DocumentPolicyType.ACTIVE_RESIDENT, severity: DocumentPolicySeverity.BLOCKING, blocking: true, enabled: true, order: 10, required: true },
      { code: "COR_PROPERTY_RELATIONSHIP", name: "Property ownership or authorized occupancy", type: DocumentPolicyType.PROPERTY_OWNERSHIP, severity: DocumentPolicySeverity.BLOCKING, blocking: true, enabled: true, order: 20, required: true },
      { code: "COR_OUTSTANDING_BALANCE", name: "Outstanding balance", type: DocumentPolicyType.OUTSTANDING_BALANCE, severity: DocumentPolicySeverity.WARNING, blocking: false, enabled: true, order: 30, required: false },
      { code: "COR_VIOLATION_STATUS", name: "Violation status", type: DocumentPolicyType.VIOLATION_STATUS, severity: DocumentPolicySeverity.WARNING, blocking: false, enabled: false, order: 40, required: false },
    ] as const;
    for (const item of policies) {
      let policy = await tx.documentPolicy.findFirst({ where: { tenantId: context.tenantId, code: item.code }, select: { id: true } });
      if (!policy) {
        policy = await tx.documentPolicy.create({
          data: {
            tenantId: context.tenantId,
            code: item.code,
            name: item.name,
            type: item.type,
            severity: item.severity,
            blocking: item.blocking,
            enabled: item.enabled,
            parameters: item.type === DocumentPolicyType.OUTSTANDING_BALANCE ? asJson({ threshold: 0 }) : undefined,
            createdById: actor.id,
            updatedById: actor.id,
          },
          select: { id: true },
        });
      }
      await tx.documentDefinitionPolicyAssignment.upsert({
        where: { tenantId_definitionId_policyId: { tenantId: context.tenantId, definitionId: definition.id, policyId: policy.id } },
        create: { tenantId: context.tenantId, definitionId: definition.id, policyId: policy.id, evaluationOrder: item.order, required: item.required, enabled: true },
        update: {},
      });
    }

    await tx.documentNumberingConfiguration.upsert({
      where: { tenantId_definitionId: { tenantId: context.tenantId, definitionId: definition.id } },
      create: {
        tenantId: context.tenantId,
        definitionId: definition.id,
        prefix: "COR",
        yearFormat: "YYYY",
        sequenceLength: 6,
        resetRule: DocumentSequenceScope.ANNUAL,
        separator: "-",
        createdById: actor.id,
        updatedById: actor.id,
      },
      update: {},
    });

    let assignedTemplateVersionId = definition.assignedTemplateVersionId;
    const assignedIsUsable = definition.assignedTemplateVersion?.tenantId === context.tenantId
      && definition.assignedTemplateVersion.status === DocumentTemplateVersionStatus.PUBLISHED
      && definition.assignedTemplateVersion.templateSet.active;
    if (!assignedIsUsable) {
      const existingPublished = await tx.documentTemplateVersion.findFirst({
        where: {
          tenantId: context.tenantId,
          status: DocumentTemplateVersionStatus.PUBLISHED,
          templateSet: { definitionId: definition.id, active: true, ownershipType: { in: [DocumentTemplateOwnership.TENANT, DocumentTemplateOwnership.CUSTOM] } },
        },
        orderBy: [{ publishedAt: "desc" }, { version: "desc" }],
      });
      if (existingPublished) {
        assignedTemplateVersionId = existingPublished.id;
      } else {
        const set = await tx.documentTemplateSet.create({
          data: {
            tenantId: context.tenantId,
            definitionId: definition.id,
            name: "Certificate of Residency Template",
            description: "Tenant-owned published baseline cloned from the HOAHub certified template.",
            active: true,
            ownershipType: DocumentTemplateOwnership.TENANT,
            sourceTemplateSetId: certified.set.id,
            sourceTemplateVersionId: certified.version.id,
            upgradeCompatible: true,
            restorable: true,
            editable: true,
            createdById: actor.id,
            updatedById: actor.id,
          },
        });
        const version = await tx.documentTemplateVersion.create({
          data: {
            tenantId: context.tenantId,
            templateSetId: set.id,
            version: 1,
            status: DocumentTemplateVersionStatus.PUBLISHED,
            ownershipType: DocumentTemplateOwnership.TENANT,
            schemaVersion: certified.version.schemaVersion,
            definitionJson: asJson(certified.version.definitionJson),
            previewMetadata: asJson({ inheritedFromCertified: true, certifiedKey: CERTIFICATE_OF_RESIDENCY_CERTIFIED_KEY }),
            publishedAt: new Date(),
            publishedById: actor.id,
            createdById: actor.id,
            sourceVersionId: certified.version.id,
            cloneSourceVersion: certified.version.version,
            clonedAt: new Date(),
            upgradeCompatible: true,
            restorable: true,
          },
        });
        assignedTemplateVersionId = version.id;
      }
      await tx.documentDefinition.update({
        where: { id: definition.id },
        data: { assignedTemplateVersionId, version: { increment: 1 }, updatedById: actor.id },
      });
    }

    await writeDocumentAudit({
      context,
      action: "PROVISION_CERTIFICATE_OF_RESIDENCY",
      entityType: "DocumentDefinition",
      entityId: definition.id,
      after: { createdDefinition, workflowId: workflow.id, assignedTemplateVersionId },
      client: tx,
    });
    return { definitionId: definition.id, createdDefinition, assignedTemplateVersionId, certifiedVersionId: certified.version.id };
  });
}

function block(
  id: string,
  type: Parameters<typeof typedBlock>[0],
  section: Parameters<typeof typedBlock>[1],
  order: number,
  content: string,
  required: boolean,
  style: NonNullable<ReturnType<typeof typedBlock>["style"]> = {},
) {
  return typedBlock(type, section, { id, order, content, required, style });
}

function typedBlock(
  type: DocumentTemplateDefinition["sections"]["body"][number]["type"],
  section: DocumentTemplateDefinition["sections"]["body"][number]["section"],
  value: Omit<DocumentTemplateDefinition["sections"]["body"][number], "type" | "section" | "visible">,
) {
  return { ...value, type, section, visible: true };
}

function asJson(value: unknown): Prisma.InputJsonValue {
  return JSON.parse(JSON.stringify(value)) as Prisma.InputJsonValue;
}
