export type DocumentRuntimeErrorCode =
  | "AUTHENTICATION_REQUIRED"
  | "TENANT_CONTEXT_MISSING"
  | "PERMISSION_DENIED"
  | "NOT_FOUND"
  | "CROSS_TENANT"
  | "VALIDATION_FAILED"
  | "CONFLICT"
  | "INVALID_STATE"
  | "POLICY_BLOCKED"
  | "WORKFLOW_BLOCKED"
  | "DUPLICATE_NUMBER"
  | "VERIFICATION_INVALID"
  | "VERIFICATION_REVOKED"
  | "VERIFICATION_EXPIRED"
  | "CONCURRENCY_CONFLICT"
  | "CAPABILITY_UNSUPPORTED"
  | "REQUEST_INCOMPLETE"
  | "ATTACHMENT_MISSING"
  | "APPROVAL_INCOMPLETE"
  | "TEMPLATE_UNAVAILABLE"
  | "DOCUMENT_TEMPLATE_VERSION_NOT_AVAILABLE"
  | "TEMPLATE_INVALID"
  | "PLACEHOLDER_UNRESOLVED"
  | "PLACEHOLDER_UNAUTHORIZED"
  | "RENDER_VALIDATION_FAILED"
  | "RENDER_FAILED"
  | "OFFICIAL_VERIFICATION_CONTEXT_MISSING"
  | "NUMBER_ALLOCATION_FAILED"
  | "VERIFICATION_CREATION_FAILED"
  | "SNAPSHOT_PERSISTENCE_FAILED"
  | "DUPLICATE_ISSUANCE"
  | "RELEASE_BLOCKED"
  | "STORAGE_FAILURE"
  | "INTERNAL_GENERATION_FAILURE";

export class DocumentRuntimeError extends Error {
  constructor(public readonly code: DocumentRuntimeErrorCode, message: string, public readonly details?: unknown) {
    super(message);
    this.name = "DocumentRuntimeError";
  }
}
