import {
  BillingFrequency,
  PlatformInvoiceStatus,
  PlatformPaymentMethod,
  TenantStatus,
  TenantSuspensionReason,
} from "@prisma/client";
import { notFound } from "next/navigation";
import { PlatformTenantTabs } from "@/components/platform-tenant-tabs";
import {
  assignTenantSubscriptionAction,
  generateTenantInvoiceAction,
  recordPlatformManualPaymentAction,
  reinstateTenantAction,
  saveTenantBillingProfileAction,
  suspendTenantAction,
} from "@/lib/actions/platform-billing";
import { getTenantCommercialSnapshot, listPlatformPlans } from "@/lib/services/platform-billing";

function money(value: number, currency = "PHP") {
  return new Intl.NumberFormat("en-PH", { style: "currency", currency, maximumFractionDigits: 2 }).format(value);
}

export default async function TenantBillingPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ success?: string; error?: string }> }) {
  const { id } = await params;
  const query = await searchParams;
  const [snapshot, plans] = await Promise.all([getTenantCommercialSnapshot(id), listPlatformPlans()]);
  if (!snapshot) notFound();
  const { tenant, subscription, billingProfile, invoices, payments, activeSuspension, outstanding } = snapshot;
  const openInvoices = invoices.filter((invoice) => [PlatformInvoiceStatus.OPEN, PlatformInvoiceStatus.PARTIALLY_PAID, PlatformInvoiceStatus.OVERDUE].includes(invoice.status));
  return <div>
    <div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-black uppercase tracking-wider text-leaf-700">{tenant.name}</p><h1 className="text-3xl font-black text-slate-950">Subscription & Billing</h1><p className="mt-2 max-w-3xl text-slate-600">Commercial control center for the HOAHub subscription, invoices, payments, billing profile, and service lifecycle.</p></div><span className={`rounded-full px-4 py-2 text-sm font-black ${tenant.status === TenantStatus.ACTIVE ? "bg-emerald-100 text-emerald-800" : "bg-amber-100 text-amber-900"}`}>{tenant.status}</span></div>
    <PlatformTenantTabs tenantId={id} active="billing" />
    {query.success && <p className="mt-4 rounded-xl bg-emerald-50 p-3 text-sm font-semibold text-emerald-800">{query.success}</p>}
    {query.error && <p className="mt-4 rounded-xl bg-rose-50 p-3 text-sm font-semibold text-rose-800">{query.error}</p>}

    <section className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-5">
      <Metric label="Plan" value={subscription?.plan.name || tenant.subscriptionPlan || "Unassigned"} />
      <Metric label="Subscription" value={subscription?.status.replaceAll("_", " ") || tenant.subscriptionStatus.replaceAll("_", " ")} />
      <Metric label="Outstanding AR" value={money(outstanding, subscription?.currency || tenant.currency)} />
      <Metric label="Next billing" value={subscription?.nextBillingDate?.toLocaleDateString("en-PH") || "Not scheduled"} />
      <Metric label="Users" value={tenant._count.users} />
    </section>

    <section className="mt-6 grid gap-5 xl:grid-cols-2">
      <article className="rounded-2xl border bg-white p-5 sm:p-6"><h2 className="text-xl font-black">Subscription contract</h2><p className="mt-1 text-sm text-slate-500">Assigning a new plan closes the previous active commercial subscription but preserves its invoices and audit history.</p>
        {subscription && <div className="mt-4 rounded-2xl bg-slate-50 p-4 text-sm"><p className="font-black text-slate-900">Current: {subscription.plan.name}</p><div className="mt-2 grid grid-cols-2 gap-3 text-slate-600"><span>{subscription.billingFrequency}</span><span>{subscription.agreedPrice == null ? "Plan pricing" : money(Number(subscription.agreedPrice), subscription.currency)}</span><span>{subscription.autoPayEnabled ? "AutoPay enabled" : "Manual/online pay"}</span><span>{subscription.trialEndsAt ? `Trial ends ${subscription.trialEndsAt.toLocaleDateString("en-PH")}` : "No active trial"}</span></div></div>}
        <form action={assignTenantSubscriptionAction} className="mt-5 grid gap-3 sm:grid-cols-2"><input type="hidden" name="tenantId" value={tenant.id} /><label className="sm:col-span-2"><span className="label">Plan</span><select className="field" name="planId" defaultValue={subscription?.planId || ""} required><option value="" disabled>Select active plan</option>{plans.filter((plan) => plan.active).map((plan) => <option key={plan.id} value={plan.id}>{plan.name} ({plan.code})</option>)}</select></label><label><span className="label">Billing frequency</span><select className="field" name="billingFrequency" defaultValue={subscription?.billingFrequency || BillingFrequency.MONTHLY}>{Object.values(BillingFrequency).map((value) => <option key={value}>{value}</option>)}</select></label><label><span className="label">Trial days</span><input className="field" type="number" min="0" max="365" name="trialDays" defaultValue={subscription ? "0" : "14"} /></label><label><span className="label">Agreed price override</span><input className="field" type="number" min="0" step="0.01" name="agreedPrice" defaultValue={subscription?.agreedPrice?.toString() || ""} placeholder="Use plan price" /></label><label><span className="label">Discount per cycle</span><input className="field" type="number" min="0" step="0.01" name="discount" defaultValue={subscription?.discount.toString() || "0"} /></label><button className="btn-primary sm:col-span-2">{subscription ? "Replace subscription contract" : "Assign subscription"}</button></form>
      </article>

      <article className="rounded-2xl border bg-white p-5 sm:p-6"><h2 className="text-xl font-black">Billing identity</h2><p className="mt-1 text-sm text-slate-500">Used for platform invoices and payment communications. This is separate from the HOA's homeowner billing configuration.</p><form action={saveTenantBillingProfileAction} className="mt-5 grid gap-3 sm:grid-cols-2"><input type="hidden" name="tenantId" value={tenant.id} /><label className="sm:col-span-2"><span className="label">Legal / billing name</span><input className="field" name="legalBusinessName" defaultValue={billingProfile?.legalBusinessName || tenant.name} /></label><label><span className="label">Billing email</span><input className="field" type="email" name="billingEmail" defaultValue={billingProfile?.billingEmail || tenant.email || ""} /></label><label><span className="label">Secondary billing email</span><input className="field" type="email" name="secondaryBillingEmail" defaultValue={billingProfile?.secondaryBillingEmail || ""} /></label><label><span className="label">Contact person</span><input className="field" name="contactPerson" defaultValue={billingProfile?.contactPerson || ""} /></label><label><span className="label">Contact number</span><input className="field" name="contactNumber" defaultValue={billingProfile?.contactNumber || tenant.contactNumber || ""} /></label><label><span className="label">TIN</span><input className="field" name="tinNumber" defaultValue={billingProfile?.tinNumber || tenant.tinNumber || ""} /></label><label><span className="label">VAT status</span><input className="field" name="vatStatus" defaultValue={billingProfile?.vatStatus || ""} placeholder="Configure after tax review" /></label><label><span className="label">Payment terms (days)</span><input className="field" type="number" min="0" max="365" name="paymentTermsDays" defaultValue={billingProfile?.paymentTermsDays || 15} /></label><label><span className="label">Payment preference</span><input className="field" name="paymentMethodPreference" defaultValue={billingProfile?.paymentMethodPreference || "ONLINE"} /></label><label className="sm:col-span-2"><span className="label">Billing address</span><textarea className="field min-h-20" name="billingAddress" defaultValue={billingProfile?.billingAddress || tenant.address || ""} /></label><label className="sm:col-span-2"><span className="label">Invoice note</span><textarea className="field min-h-20" name="invoiceNotes" defaultValue={billingProfile?.invoiceNotes || ""} /></label><label className="flex items-center gap-3 text-sm font-semibold"><input className="size-5" type="checkbox" name="purchaseOrderRequired" defaultChecked={billingProfile?.purchaseOrderRequired || false} />Purchase order required</label><button className="btn-secondary sm:col-span-2">Save billing profile</button></form></article>
    </section>

    <section className="mt-6 rounded-2xl border bg-white p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="text-xl font-black">Invoices</h2><p className="mt-1 text-sm text-slate-500">Finalized platform receivables. Homeowner bills are intentionally not shown here.</p></div>{subscription && <form action={generateTenantInvoiceAction}><input type="hidden" name="tenantId" value={tenant.id} /><button className="btn-primary">Generate bill</button></form>}</div>
      <div className="mt-5 overflow-auto"><table className="min-w-[900px] w-full text-sm"><thead className="bg-slate-50 text-left"><tr><th className="p-3">Invoice</th><th className="p-3">Coverage</th><th className="p-3">Issued / Due</th><th className="p-3">Total</th><th className="p-3">Paid</th><th className="p-3">Balance</th><th className="p-3">Status</th></tr></thead><tbody>{invoices.map((invoice) => <tr key={invoice.id} className="border-t"><td className="p-3 font-black">{invoice.invoiceNumber}</td><td className="p-3">{invoice.billingPeriodStart.toLocaleDateString("en-PH")} – {invoice.billingPeriodEnd.toLocaleDateString("en-PH")}</td><td className="p-3">{invoice.issueDate.toLocaleDateString("en-PH")}<br/><span className="text-xs text-slate-500">Due {invoice.dueDate.toLocaleDateString("en-PH")}</span></td><td className="p-3 font-bold">{money(Number(invoice.total), invoice.currency)}</td><td className="p-3">{money(Number(invoice.amountPaid), invoice.currency)}</td><td className="p-3 font-black">{money(Number(invoice.outstandingBalance), invoice.currency)}</td><td className="p-3"><span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-black">{invoice.status.replaceAll("_", " ")}</span></td></tr>)}</tbody></table></div>{!invoices.length && <p className="mt-5 rounded-xl border border-dashed p-8 text-center text-sm text-slate-500">No platform invoices yet.</p>}
    </section>

    {openInvoices.length > 0 && <section className="mt-6 rounded-2xl border bg-white p-5 sm:p-6"><h2 className="text-xl font-black">Record external/manual payment</h2><p className="mt-1 text-sm text-slate-500">Use for bank transfer, cash, check, or approved manual collection. PayMongo checkout will post to the same platform payment ledger through a verified webhook.</p><form action={recordPlatformManualPaymentAction} className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><input type="hidden" name="tenantId" value={tenant.id} /><label className="xl:col-span-2"><span className="label">Invoice</span><select className="field" name="invoiceId" required>{openInvoices.map((invoice) => <option key={invoice.id} value={invoice.id}>{invoice.invoiceNumber} · {money(Number(invoice.outstandingBalance), invoice.currency)} due</option>)}</select></label><label><span className="label">Amount</span><input className="field" name="amount" type="number" min="0.01" step="0.01" required /></label><label><span className="label">Method</span><select className="field" name="method" defaultValue={PlatformPaymentMethod.BANK_TRANSFER}>{[PlatformPaymentMethod.BANK_TRANSFER, PlatformPaymentMethod.CASH, PlatformPaymentMethod.CHECK, PlatformPaymentMethod.MANUAL, PlatformPaymentMethod.OTHER].map((value) => <option key={value}>{value.replaceAll("_", " ")}</option>)}</select></label><label><span className="label">Reference</span><input className="field" name="referenceNumber" placeholder="Optional external ref" /></label><button className="btn-primary sm:col-span-2 xl:col-span-5">Post payment</button></form></section>}

    <section className="mt-6 grid gap-5 xl:grid-cols-2"><article className="rounded-2xl border bg-white p-5 sm:p-6"><h2 className="text-xl font-black">Payment history</h2><div className="mt-4 space-y-3">{payments.map((payment) => <div key={payment.id} className="rounded-xl border p-4 text-sm"><div className="flex items-start justify-between gap-3"><div><p className="font-black">{payment.paymentReference}</p><p className="text-xs text-slate-500">{payment.gateway} · {payment.method.replaceAll("_", " ")}</p></div><p className="font-black text-pine-900">{money(Number(payment.amount), payment.currency)}</p></div><p className="mt-2 text-xs text-slate-500">{payment.status} · {payment.paidAt?.toLocaleString("en-PH") || payment.receivedAt.toLocaleString("en-PH")}</p></div>)}{!payments.length && <p className="rounded-xl border border-dashed p-6 text-center text-sm text-slate-500">No platform payments recorded.</p>}</div></article>
      <article className="rounded-2xl border bg-white p-5 sm:p-6"><h2 className="text-xl font-black">Service lifecycle</h2>{activeSuspension && <div className="mt-4 rounded-xl bg-amber-50 p-4 text-sm text-amber-950"><p className="font-black">Active suspension: {activeSuspension.reason.replaceAll("_", " ")}</p><p className="mt-1">{activeSuspension.notes || "No suspension note."}</p><p className="mt-2 text-xs">Auto-reinstate: {activeSuspension.autoReinstate ? "Enabled for eligible payment recovery" : "No"}</p></div>}
        {tenant.status === TenantStatus.ACTIVE ? <form action={suspendTenantAction} className="mt-5 space-y-3"><input type="hidden" name="tenantId" value={tenant.id} /><label><span className="label">Suspension reason</span><select className="field" name="reason" defaultValue={TenantSuspensionReason.NON_PAYMENT}>{Object.values(TenantSuspensionReason).map((value) => <option key={value}>{value.replaceAll("_", " ")}</option>)}</select></label><label><span className="label">Reason / operator notes</span><textarea className="field min-h-24" name="notes" required /></label><label className="flex items-center gap-3 text-sm font-semibold"><input className="size-5" type="checkbox" name="autoReinstate" defaultChecked />Automatically reinstate eligible non-payment suspension after balance is settled</label><button className="w-full rounded-xl bg-rose-700 px-4 py-3 font-black text-white hover:bg-rose-800">Suspend tenant</button></form> : <form action={reinstateTenantAction} className="mt-5 space-y-3"><input type="hidden" name="tenantId" value={tenant.id} /><label><span className="label">Reinstatement note</span><textarea className="field min-h-24" name="notes" placeholder="Reason for restoring service" /></label><button className="btn-primary w-full">Reinstate tenant</button></form>}
      </article></section>
  </div>;
}

function Metric({ label, value }: { label: string; value: string | number }) {
  return <article className="rounded-2xl border bg-white p-5 shadow-sm"><p className="text-xs font-black uppercase tracking-wider text-slate-500">{label}</p><p className="mt-2 break-words text-xl font-black text-pine-950">{value}</p></article>;
}
