ALTER TABLE `User` MODIFY `role` ENUM('SUPER_ADMIN','PLATFORM_ADMIN','HOA_ADMIN','BILLING_MANAGER','PAYROLL_MANAGER','STAFF','SYSTEM_ADMIN','ADMIN','HOMEOWNER','EMPLOYEE') NOT NULL DEFAULT 'HOMEOWNER';

CREATE TABLE `TenantModuleEntitlement` (
  `id` VARCHAR(191) NOT NULL,
  `tenantId` VARCHAR(191) NOT NULL,
  `module` ENUM('BILLING','PAYROLL','ATTENDANCE','DOCUMENTS','REPORTS','CHAT','ANNOUNCEMENTS','EVENTS','COMPLAINTS','VEHICLES','VISITORS','CONTRACTORS','CONSTRUCTION','FACILITY_RESERVATION','LOANS','CASH_ADVANCE') NOT NULL,
  `enabled` BOOLEAN NOT NULL DEFAULT true,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `TenantModuleEntitlement_tenantId_module_key`(`tenantId`, `module`),
  INDEX `TenantModuleEntitlement_tenantId_enabled_idx`(`tenantId`, `enabled`),
  CONSTRAINT `TenantModuleEntitlement_tenantId_fkey` FOREIGN KEY (`tenantId`) REFERENCES `Tenant`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `TenantAdvisory` (
  `id` VARCHAR(191) NOT NULL,
  `tenantId` VARCHAR(191) NOT NULL,
  `message` TEXT NOT NULL,
  `active` BOOLEAN NOT NULL DEFAULT true,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `TenantAdvisory_tenantId_active_idx`(`tenantId`, `active`),
  CONSTRAINT `TenantAdvisory_tenantId_fkey` FOREIGN KEY (`tenantId`) REFERENCES `Tenant`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `TenantSequence` (
  `id` VARCHAR(191) NOT NULL,
  `tenantId` VARCHAR(191) NOT NULL,
  `scope` VARCHAR(191) NOT NULL,
  `year` INTEGER NOT NULL,
  `nextValue` INTEGER NOT NULL DEFAULT 1,
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `TenantSequence_tenantId_scope_year_key`(`tenantId`, `scope`, `year`),
  CONSTRAINT `TenantSequence_tenantId_fkey` FOREIGN KEY (`tenantId`) REFERENCES `Tenant`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

INSERT INTO `TenantModuleEntitlement` (`id`,`tenantId`,`module`,`enabled`,`createdAt`,`updatedAt`)
SELECT CONCAT('default_', LOWER(`module_name`)), 'tenant_pagsibol4b_default', `module_name`, true, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)
FROM (
  SELECT 'BILLING' module_name UNION ALL SELECT 'PAYROLL' UNION ALL SELECT 'ATTENDANCE' UNION ALL SELECT 'DOCUMENTS'
  UNION ALL SELECT 'REPORTS' UNION ALL SELECT 'CHAT' UNION ALL SELECT 'ANNOUNCEMENTS' UNION ALL SELECT 'EVENTS'
  UNION ALL SELECT 'COMPLAINTS' UNION ALL SELECT 'VEHICLES' UNION ALL SELECT 'VISITORS' UNION ALL SELECT 'CONTRACTORS'
  UNION ALL SELECT 'CONSTRUCTION' UNION ALL SELECT 'FACILITY_RESERVATION' UNION ALL SELECT 'LOANS' UNION ALL SELECT 'CASH_ADVANCE'
) modules;
