import Link from "next/link";
import { TenantStatus } from "@prisma/client";
import { prisma } from "@/lib/db";

export default async function TenantsPage({ searchParams }: { searchParams: Promise<{ q?: string; status?: string; page?: string; error?: string }> }) {
  const query = await searchParams; const q = String(query.q || "").trim(); const page = Math.max(1, Number(query.page) || 1); const pageSize = 12;
  const status = Object.values(TenantStatus).includes(query.status as TenantStatus) ? query.status as TenantStatus : undefined;
  const where = { ...(status ? { status } : {}), ...(q ? { OR: [{ name: { contains: q } }, { slug: { contains: q } }, { shortName: { contains: q } }] } : {}) };
  const [tenants, count, totalUsers, homeowners, payments, active, suspended] = await Promise.all([prisma.tenant.findMany({ where, include: { _count: { select: { users: true } } }, orderBy: { createdAt: "desc" }, skip: (page - 1) * pageSize, take: pageSize }), prisma.tenant.count({ where }), prisma.user.count(), prisma.homeownerProfile.count(), prisma.payment.count(), prisma.tenant.count({ where: { status: "ACTIVE" } }), prisma.tenant.count({ where: { status: "SUSPENDED" } })]);
  const pages = Math.max(1, Math.ceil(count / pageSize));
  return <><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-bold uppercase tracking-wider text-leaf-700">Platform overview</p><h1 className="text-3xl font-black text-slate-900 sm:text-4xl">Tenant Management</h1><p className="mt-2 text-slate-600">Monitor HOA access, subscriptions, users, and health from one workspace.</p></div><Link className="btn-primary" href="/platform/tenants/new">Onboard HOA</Link></div>
  <section className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{[["Total tenants", await prisma.tenant.count()], ["Active", active], ["Suspended", suspended], ["Platform users", totalUsers], ["Homeowners", homeowners], ["Transactions", payments]].map(([label,value]) => <article key={String(label)} className="rounded-2xl border bg-white p-5 shadow-sm"><p className="text-xs font-bold uppercase tracking-wider text-slate-500">{label}</p><p className="mt-2 text-3xl font-black text-pine-900">{value}</p></article>)}</section>
  {query.error && <p className="mt-5 rounded-xl bg-rose-50 p-3 text-rose-800">{query.error}</p>}
  <form className="mt-6 grid gap-3 rounded-2xl border bg-white p-4 sm:grid-cols-[1fr_180px_auto]"><input className="field" name="q" defaultValue={q} placeholder="Search HOA name or slug" /><select className="field" name="status" defaultValue={status || ""}><option value="">All statuses</option>{Object.values(TenantStatus).map((value) => <option key={value}>{value}</option>)}</select><button className="btn-secondary">Search</button></form>
  <div className="mt-4 hidden max-h-[60vh] overflow-auto rounded-2xl border bg-white md:block"><table className="min-w-full text-sm"><thead className="sticky top-0 bg-slate-100 text-left"><tr><th className="p-4">Association</th><th className="p-4">Slug / Login URL</th><th className="p-4">Plan</th><th className="p-4">Health</th><th className="p-4">Users</th><th className="p-4">Actions</th></tr></thead><tbody>{tenants.map((tenant) => <tr key={tenant.id} className="border-t hover:bg-slate-50"><td className="p-4"><p className="font-black">{tenant.name}</p><p className="text-xs text-slate-500">{tenant.shortName}</p></td><td className="max-w-xs p-4"><Link className="break-all font-bold text-blue-700 hover:underline" href={`/${tenant.slug}/login`} target="_blank">/{tenant.slug}/login</Link></td><td className="p-4">{tenant.subscriptionPlan}<br/><span className="text-xs text-slate-500">{tenant.subscriptionStatus}</span></td><td className="p-4"><span className={`rounded-full px-2 py-1 text-xs font-bold ${tenant.status === "ACTIVE" ? "bg-emerald-100 text-emerald-800" : "bg-amber-100 text-amber-900"}`}>{tenant.status}</span></td><td className="p-4">{tenant._count.users}</td><td className="p-4"><Link className="font-bold text-pine-700" href={`/platform/tenants/${tenant.id}`}>Manage</Link> <span className="text-slate-300">|</span> <Link className="font-bold text-blue-700" href={`/platform/tenants/${tenant.id}/users`}>Users</Link></td></tr>)}</tbody></table></div>
  <div className="mt-4 grid gap-3 md:hidden">{tenants.map((tenant) => <article key={tenant.id} className="rounded-2xl border bg-white p-5"><div className="flex items-start justify-between gap-3"><h2 className="font-black text-slate-900">{tenant.name}</h2><span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-bold">{tenant.status}</span></div><Link className="mt-3 block break-all text-sm font-bold text-blue-700" href={`/${tenant.slug}/login`} target="_blank">/{tenant.slug}/login</Link><p className="mt-3 text-sm text-slate-600">{tenant.subscriptionPlan} · {tenant._count.users} users</p><div className="mt-4 flex gap-2"><Link className="btn-secondary flex-1 text-center" href={`/platform/tenants/${tenant.id}`}>Manage</Link><Link className="btn-secondary flex-1 text-center" href={`/platform/tenants/${tenant.id}/users`}>Users</Link></div></article>)}</div>
  {!tenants.length && <div className="mt-4 rounded-2xl border border-dashed bg-white p-10 text-center text-slate-600">No tenants match the selected filters.</div>}<div className="mt-5 flex items-center justify-between text-sm"><span>Page {page} of {pages}</span><div className="flex gap-2">{page > 1 && <Link className="btn-secondary" href={`?q=${encodeURIComponent(q)}&status=${status || ""}&page=${page-1}`}>Previous</Link>}{page < pages && <Link className="btn-secondary" href={`?q=${encodeURIComponent(q)}&status=${status || ""}&page=${page+1}`}>Next</Link>}</div></div></>;
}
