import { StandardTable } from "@/components/standard-table";
import { Role } from "@prisma/client";
import Link from "next/link";
import { notFound } from "next/navigation";
import { PlatformTenantTabs } from "@/components/platform-tenant-tabs";
import { PasswordInput } from "@/components/password-input";
import { createTenantUserAction, toggleTenantUserAction } from "@/lib/actions/platform";
import { prisma } from "@/lib/db";
import { roleLabel, tenantAccessRoles, tenantUserRoles } from "@/lib/tenant-roles";

export default async function TenantUsersPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ q?: string; role?: string; status?: string; type?: string; sort?: string; page?: string; success?: string; error?: string; message?: string }> }) {
  const { id } = await params; const query = await searchParams; const tenant = await prisma.tenant.findUnique({ where: { id } }); if (!tenant) notFound();
  const q = String(query.q || "").trim(); const page = Math.max(1, Number(query.page) || 1); const pageSize = 20; const role = tenantUserRoles.includes(query.role as Role) ? query.role as Role : undefined; const active = query.status === "active" ? true : query.status === "inactive" ? false : undefined;
  const typeWhere = query.type === "homeowner" ? { homeownerProfile: { isNot: null } } : query.type === "employee" ? { employeeProfile: { isNot: null } } : query.type === "staff" ? { homeownerProfile: null, employeeProfile: null } : {};
  const where = { tenantId: id, ...typeWhere, ...(role ? { role } : {}), ...(active === undefined ? {} : { active }), ...(q ? { OR: [{ name: { contains: q } }, { email: { contains: q } }, { username: { contains: q } }, { id: { contains: q } }] } : {}) };
  const orderBy = query.sort === "oldest" ? { createdAt: "asc" as const } : query.sort === "name" ? { name: "asc" as const } : query.sort === "lastLogin" ? { lastLoginAt: "desc" as const } : { createdAt: "desc" as const };
  const [users, count] = await Promise.all([prisma.user.findMany({ where, include: { homeownerProfile: { select: { id: true } }, employeeProfile: { select: { id: true, employeeNumber: true } } }, orderBy, skip: (page-1)*pageSize, take: pageSize }), prisma.user.count({ where })]); const pages = Math.max(1, Math.ceil(count/pageSize));
  const userType = (user: typeof users[number]) => user.homeownerProfile ? "Homeowner" : user.employeeProfile ? "Employee" : "HOA Personnel";
  return <div><div><p className="text-sm font-bold uppercase tracking-wider text-leaf-700">{tenant.name}</p><h1 className="text-3xl font-black text-slate-900">Tenant Users</h1><p className="mt-2 text-slate-600">Search, review, activate, and manage users assigned to this HOA.</p></div><PlatformTenantTabs tenantId={id} active="users" />{query.success && <p className="mt-4 rounded-xl bg-emerald-50 p-3 text-emerald-800">{query.message || "Tenant user record updated successfully."}</p>}{query.error && <p className="mt-4 rounded-xl bg-rose-50 p-3 text-rose-800">{query.error}</p>}
  <details className="mt-5 rounded-2xl border border-pine-200 bg-pine-50/40 p-4 open:bg-white sm:p-5"><summary className="cursor-pointer font-black text-pine-900">Add tenant access account</summary><p className="mt-2 text-sm text-slate-600">Super Admin can create every tenant administrative access type, including Tenant System Administrator. Homeowner and employee accounts should be created from their operational modules so their linked records remain complete.</p><form action={createTenantUserAction} className="mt-4 grid gap-4 sm:grid-cols-2 xl:grid-cols-3"><input type="hidden" name="tenantId" value={id}/><label><span className="label">Full name</span><input className="field" name="name" required/></label><label><span className="label">Email</span><input className="field" type="email" name="email" required/></label><label><span className="label">Username (optional)</span><input className="field" name="username"/></label><label><span className="label">Access role</span><select className="field" name="role" defaultValue="SYSTEM_ADMIN">{tenantAccessRoles.map((value) => <option key={value} value={value}>{roleLabel(value)}</option>)}</select></label><label><span className="label">Temporary password</span><PasswordInput className="field" name="password" minLength={10} autoComplete="new-password" required/></label><div className="flex items-end"><button className="btn-primary min-h-12 w-full">Create access account</button></div></form></details>
  <form className="mt-5 grid gap-3 rounded-2xl border bg-white p-4 sm:grid-cols-2 xl:grid-cols-[1fr_180px_160px_160px_160px_auto]"><input className="field" name="q" defaultValue={q} placeholder="Name, email, username, or ID" /><select className="field" name="role" defaultValue={role || ""}><option value="">All roles</option>{tenantUserRoles.map((value) => <option key={value} value={value}>{roleLabel(value)}</option>)}</select><select className="field" name="status" defaultValue={query.status || ""}><option value="">All statuses</option><option value="active">Active</option><option value="inactive">Inactive</option></select><select className="field" name="type" defaultValue={query.type || ""}><option value="">All user types</option><option value="homeowner">Homeowner</option><option value="employee">Employee</option><option value="staff">HOA Personnel</option></select><select className="field" name="sort" defaultValue={query.sort || "newest"}><option value="newest">Newest</option><option value="oldest">Oldest</option><option value="name">Name</option><option value="lastLogin">Last login</option></select><button className="btn-secondary">Apply</button></form>
  <div className="mt-4 hidden max-h-[62vh] overflow-auto rounded-2xl border bg-white lg:block"><StandardTable><table className="min-w-[1100px] text-sm"><thead className="sticky top-0 z-10 bg-slate-100 text-left"><tr>{["User ID","Full Name","Email / Username","Role","User Type","Tenant","Status","Last Login","Created","Actions"].map((h)=><th key={h} className="p-3">{h}</th>)}</tr></thead><tbody>{users.map((user)=><tr key={user.id} className="border-t hover:bg-slate-50"><td className="max-w-32 truncate p-3 font-mono text-xs" title={user.id}>{user.id}</td><td className="p-3 font-bold">{user.name}</td><td className="p-3"><p>{user.email}</p><p className="text-xs text-slate-500">{user.username || "No username"}</p></td><td className="p-3 text-xs font-bold">{user.role}</td><td className="p-3">{userType(user)}</td><td className="p-3">{tenant.shortName}</td><td className="p-3"><span className={`rounded-full px-2 py-1 text-xs font-bold ${user.active ? "bg-emerald-100 text-emerald-800" : "bg-slate-200 text-slate-700"}`}>{user.active ? "ACTIVE" : "INACTIVE"}</span></td><td className="p-3">{user.lastLoginAt?.toLocaleString() || "Never"}</td><td className="p-3">{user.createdAt.toLocaleDateString()}</td><td className="p-3"><div className="flex gap-2"><Link className="font-bold text-blue-700" href={`/platform/tenants/${id}/users/${user.id}`}>View / Edit</Link><form action={toggleTenantUserAction}><input type="hidden" name="tenantId" value={id}/><input type="hidden" name="userId" value={user.id}/><button className="font-bold text-amber-700">{user.active ? "Deactivate" : "Activate"}</button></form></div></td></tr>)}</tbody></table></StandardTable></div>
  <div className="mt-4 grid gap-3 lg:hidden">{users.map((user)=><article key={user.id} className="min-w-0 rounded-2xl border bg-white p-5"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><h2 className="break-words font-black">{user.name}</h2><p className="break-all text-sm text-slate-600">{user.email}</p></div><span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-bold">{user.active ? "ACTIVE" : "INACTIVE"}</span></div><dl className="mt-4 grid grid-cols-2 gap-3 text-sm"><div><dt className="text-slate-500">Role</dt><dd className="font-bold">{user.role}</dd></div><div><dt className="text-slate-500">Type</dt><dd>{userType(user)}</dd></div><div><dt className="text-slate-500">Last login</dt><dd>{user.lastLoginAt?.toLocaleDateString() || "Never"}</dd></div><div><dt className="text-slate-500">Created</dt><dd>{user.createdAt.toLocaleDateString()}</dd></div></dl><Link className="btn-secondary mt-4 block min-h-11 text-center" href={`/platform/tenants/${id}/users/${user.id}`}>View / Edit User</Link></article>)}</div>
  {!users.length && <div className="mt-4 rounded-2xl border border-dashed bg-white p-10 text-center text-slate-600">No tenant users match these filters.</div>}<div className="mt-5 flex items-center justify-between text-sm"><span>{count} users · Page {page} of {pages}</span><div className="flex gap-2">{page>1&&<Link className="btn-secondary" href={`?q=${encodeURIComponent(q)}&page=${page-1}`}>Previous</Link>}{page<pages&&<Link className="btn-secondary" href={`?q=${encodeURIComponent(q)}&page=${page+1}`}>Next</Link>}</div></div></div>;
}
