import { StandardTable } from "@/components/standard-table";
import { CalendarCheck2, ShieldCheck, UsersRound } from "lucide-react";
import { LeaveRequestStatus } from "@prisma/client";
import { PageHeader } from "@/components/page-header";
import { StatCard } from "@/components/stat-card";
import { StatusBadge } from "@/components/status-badge";
import { adjustEmployeeLeaveBalanceAction, deactivateLeaveTypeAction, reviewLeaveRequestAction, saveLeaveTypeAction } from "@/lib/actions/leave";
import { prisma } from "@/lib/db";
import { hasPayrollRole, leaveApprovalRoles, leaveConfigurationRoles, requirePayrollAccess } from "@/lib/payroll-access";
import { availableLeaveDays } from "@/lib/services/leave";
import { shortDate } from "@/lib/utils";

export default async function AdminLeavePage() {
  const { user, roles } = await requirePayrollAccess();
  const tenantId = user.tenantId;
  const canApprove = hasPayrollRole(roles, leaveApprovalRoles);
  const canConfigure = hasPayrollRole(roles, leaveConfigurationRoles);
  const year = new Date().getUTCFullYear();
  const [leaveTypes, requests, balances, employees] = await Promise.all([
    prisma.leaveType.findMany({ where: { tenantId }, orderBy: [{ statutoryProtected: "desc" }, { name: "asc" }] }),
    prisma.leaveRequest.findMany({ where: { tenantId }, include: { employee: true, leaveType: true, reviewedBy: true }, orderBy: [{ status: "asc" }, { createdAt: "desc" }], take: 150 }),
    prisma.employeeLeaveBalance.findMany({ where: { tenantId, year }, include: { employee: true, leaveType: true }, orderBy: [{ employee: { name: "asc" } }, { leaveType: { name: "asc" } }] }),
    prisma.employeeProfile.findMany({ where: { tenantId, status: "ACTIVE" }, orderBy: { name: "asc" } }),
  ]);
  const pending = requests.filter((request) => request.status === LeaveRequestStatus.PENDING);
  const balanceTypes = leaveTypes.filter((type) => type.active && type.requiresBalance);

  return <>
    <PageHeader eyebrow="Protected workforce data" title="Leave management" description="Configure tenant leave, review employee requests, maintain auditable balances, and preserve protected Philippine statutory definitions." />
    <section className="mb-6 grid gap-4 sm:grid-cols-3"><StatCard label="Pending requests" value={String(pending.length)} icon={CalendarCheck2} /><StatCard label="Active leave types" value={String(leaveTypes.filter((type) => type.active).length)} icon={ShieldCheck} /><StatCard label="Employees" value={String(employees.length)} icon={UsersRound} /></section>

    <section className="grid gap-6 xl:grid-cols-[minmax(0,1.2fr)_420px]">
      <div className="space-y-6">
        <section className="card"><h2 className="text-lg font-black">Leave approval queue</h2><p className="mt-1 text-sm text-slate-500">Approval creates linked paid/unpaid attendance and consumes balance atomically. Locked payroll dates fail closed.</p><div className="mt-5 space-y-3">{pending.map((request) => <article key={request.id} className="rounded-2xl border border-slate-100 bg-slate-50 p-4"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-start"><div><div className="flex flex-wrap items-center gap-2"><h3 className="font-black">{request.employee.name}</h3><StatusBadge status={request.status} /></div><p className="mt-1 text-sm font-bold text-pine-700">{request.leaveType.name} · {Number(request.requestedDays).toFixed(2)} day(s)</p><p className="text-sm text-slate-500">{shortDate(request.startDate)} – {shortDate(request.endDate)}</p><p className="mt-2 text-sm text-slate-600">{request.reason}</p>{request.evidenceReference && <p className="mt-1 text-xs text-slate-500">Evidence reference: {request.evidenceReference}</p>}</div>{request.leaveType.statutoryProtected && <span className="rounded-full bg-pine-100 px-2 py-1 text-[10px] font-black uppercase text-pine-700">Protected formula</span>}</div>{canApprove && <form action={reviewLeaveRequestAction} className="mt-4 grid gap-2 sm:grid-cols-[1fr_auto_auto]"><input type="hidden" name="id" value={request.id} /><input className="field min-h-10 py-2 text-xs" name="reviewRemarks" maxLength={500} placeholder="Approval notes or required rejection reason" /><button className="btn-primary" name="decision" value="APPROVED">Approve</button><button className="btn-danger" name="decision" value="REJECTED">Reject</button></form>}</article>)}{!pending.length && <p className="py-10 text-center text-sm text-slate-500">No pending leave requests.</p>}</div></section>

        <section className="card"><h2 className="text-lg font-black">Recent request history</h2><div className="table-wrap mt-4"><StandardTable><table className="data-table"><thead><tr><th>Employee</th><th>Leave</th><th>Dates</th><th>Days</th><th>Status</th><th>Reviewer</th></tr></thead><tbody>{requests.map((request) => <tr key={request.id}><td>{request.employee.name}</td><td>{request.leaveType.name}</td><td>{shortDate(request.startDate)} – {shortDate(request.endDate)}</td><td>{Number(request.requestedDays).toFixed(2)}</td><td><StatusBadge status={request.status} /></td><td>{request.reviewedBy?.name ?? "—"}</td></tr>)}</tbody></table></StandardTable></div></section>
      </div>

      <div className="space-y-6">
        {canConfigure && <section className="card"><h2 className="text-lg font-black">Add tenant leave type</h2><p className="mt-1 text-sm text-slate-500">Custom policies are version-safe because each request snapshots its resolved type. Protected statutory rows cannot be edited.</p><LeaveTypeForm /></section>}
        {canConfigure && <section className="card"><h2 className="text-lg font-black">Adjust annual balance</h2><form action={adjustEmployeeLeaveBalanceAction} className="mt-4 space-y-3"><div><label className="label">Employee</label><select className="field" name="employeeId" required defaultValue=""><option value="" disabled>Select employee</option>{employees.map((employee) => <option key={employee.id} value={employee.id}>{employee.name} · {employee.employeeNumber}</option>)}</select></div><div><label className="label">Leave type</label><select className="field" name="leaveTypeId" required defaultValue=""><option value="" disabled>Select balance type</option>{balanceTypes.map((type) => <option key={type.id} value={type.id}>{type.name}</option>)}</select></div><div className="grid grid-cols-2 gap-3"><div><label className="label">Year</label><input className="field" name="year" type="number" min={2000} max={2200} defaultValue={year} required /></div><div><label className="label">Days (+/-)</label><input className="field" name="days" type="number" step="0.01" min={-366} max={366} required /></div></div><div><label className="label">Audit reason</label><textarea className="field min-h-20" name="reason" minLength={10} maxLength={500} required /></div><button className="btn-primary w-full">Record adjustment</button></form></section>}

        <section className="card"><h2 className="text-lg font-black">Leave type registry</h2><div className="mt-4 space-y-3">{leaveTypes.map((type) => <article key={type.id} className="rounded-2xl border border-slate-100 p-4"><div className="flex items-start justify-between gap-3"><div><h3 className="font-black">{type.name}</h3><p className="text-xs text-slate-500">{type.code} · {type.payrollTreatment.replaceAll("_", " ")} · {type.dayCountingMethod.replaceAll("_", " ")}</p></div>{type.statutoryProtected ? <ShieldCheck className="size-5 text-pine-600" /> : <StatusBadge status={type.active ? "ACTIVE" : "INACTIVE"} />}</div>{type.description && <p className="mt-2 text-sm text-slate-600">{type.description}</p>}<p className="mt-2 text-xs text-slate-500">{type.requiresBalance ? `${Number(type.annualEntitlementDays ?? 0).toFixed(2)} days/year` : "No annual balance"}{type.maximumDaysPerRequest ? ` · Max ${Number(type.maximumDaysPerRequest)} per request` : ""}{type.statutoryAuthority ? ` · ${type.statutoryAuthority}` : ""}</p>{canConfigure && !type.statutoryProtected && <details className="mt-3"><summary className="cursor-pointer text-xs font-black text-pine-700">Edit custom policy</summary><LeaveTypeForm type={type} />{type.active && <form action={deactivateLeaveTypeAction} className="mt-3"><input type="hidden" name="id" value={type.id} /><button className="btn-danger text-xs">Deactivate custom type</button></form>}</details>}</article>)}</div></section>

        <section className="card"><h2 className="text-lg font-black">{year} balances</h2><div className="mt-4 space-y-2">{balances.map((balance) => <div key={balance.id} className="rounded-xl bg-slate-50 p-3 text-sm"><div className="flex justify-between gap-3"><span className="font-bold">{balance.employee.name} · {balance.leaveType.name}</span><span className="font-black text-pine-700">{availableLeaveDays(balance).toFixed(2)} available</span></div><p className="mt-1 text-xs text-slate-500">{Number(balance.entitlementDays).toFixed(2)} entitlement + {Number(balance.carriedForwardDays).toFixed(2)} carried + {Number(balance.adjustmentDays).toFixed(2)} adjustments − {Number(balance.usedDays).toFixed(2)} used</p></div>)}{!balances.length && <p className="text-sm text-slate-500">Balances are created when an eligible employee first requests or receives an adjustment.</p>}</div></section>
      </div>
    </section>
  </>;
}

function LeaveTypeForm({ type }: { type?: { id: string; code: string; name: string; description: string | null; payrollTreatment: string; requiresBalance: boolean; annualEntitlementDays: unknown; eligibilityServiceMonths: number; maximumDaysPerRequest: unknown; dayCountingMethod: string; active: boolean } }) {
  return <form action={saveLeaveTypeAction} className="mt-4 space-y-3">{type && <input type="hidden" name="id" value={type.id} />}<div className="grid grid-cols-2 gap-3"><div><label className="label">Code</label><input className="field" name="code" defaultValue={type?.code} required maxLength={80} /></div><div><label className="label">Name</label><input className="field" name="name" defaultValue={type?.name} required maxLength={160} /></div></div><div><label className="label">Description</label><textarea className="field min-h-20" name="description" defaultValue={type?.description ?? ""} maxLength={2000} /></div><div className="grid grid-cols-2 gap-3"><div><label className="label">Payroll treatment</label><select className="field" name="payrollTreatment" defaultValue={type?.payrollTreatment ?? "PAID_LEAVE"}><option value="PAID_LEAVE">Paid leave</option><option value="UNPAID_LEAVE">Unpaid leave</option><option value="TRACK_ONLY">Track only</option></select></div><div><label className="label">Counting</label><select className="field" name="dayCountingMethod" defaultValue={type?.dayCountingMethod ?? "WORKING_DAYS"}><option value="WORKING_DAYS">Working days</option><option value="CALENDAR_DAYS">Calendar days</option></select></div></div><div className="grid grid-cols-3 gap-3"><div><label className="label">Days/year</label><input className="field" name="annualEntitlementDays" type="number" min={0} max={366} step="0.01" defaultValue={type?.annualEntitlementDays == null ? "" : Number(type.annualEntitlementDays)} /></div><div><label className="label">Service months</label><input className="field" name="eligibilityServiceMonths" type="number" min={0} max={600} defaultValue={type?.eligibilityServiceMonths ?? 0} required /></div><div><label className="label">Max/request</label><input className="field" name="maximumDaysPerRequest" type="number" min={0.01} max={366} step="0.01" defaultValue={type?.maximumDaysPerRequest == null ? "" : Number(type.maximumDaysPerRequest)} /></div></div><div className="flex flex-wrap gap-4 text-sm"><label className="flex items-center gap-2"><input type="checkbox" name="requiresBalance" defaultChecked={type?.requiresBalance ?? true} /> Uses annual balance</label><label className="flex items-center gap-2"><input type="checkbox" name="active" defaultChecked={type?.active ?? true} /> Active</label></div><button className="btn-primary w-full">{type ? "Save custom policy" : "Add leave type"}</button></form>;
}
