import Link from "next/link";
import { Eye, History, Paperclip, Printer, Save } from "lucide-react";
import { PaymentRequestType, Prisma, Role } from "@prisma/client";
import { PageHeader } from "@/components/page-header";
import { PaymentForm } from "@/components/payment-form";
import { PaymentVoidForm } from "@/components/payment-void-form";
import { SearchInput } from "@/components/ui";
import { StatusBadge } from "@/components/status-badge";
import { SubmitButton } from "@/components/ui";
import { approvePaymentRequestAction, rejectPaymentRequestAction } from "@/lib/actions/payment-requests";
import { updatePaymentAmountAction } from "@/lib/actions/payments";
import { requireUser } from "@/lib/auth";
import { prisma } from "@/lib/db";
import { paymentCoverageLabel } from "@/lib/payment-coverage";
import { collectionLabel, inputDate, money, monthLabel, shortDate } from "@/lib/utils";

type Query = { q?: string; homeownerId?: string; status?: string; paymentType?: string; collectionType?: string; method?: string; dateFrom?: string; dateTo?: string; sort?: string; requestPage?: string; paymentPage?: string; historyPage?: string; error?: string; success?: string; message?: string };
export default async function PaymentsPage({ searchParams }: { searchParams: Promise<Query> }) {
  const admin = await requireUser(Role.ADMIN);
  const query = await searchParams; const q = query.q?.trim() || ""; const requestPage = Math.max(1, Number(query.requestPage) || 1); const paymentPage = Math.max(1, Number(query.paymentPage) || 1); const historyPage = Math.max(1, Number(query.historyPage) || 1); const pageSize = 15;
  const dateRange = { ...(query.dateFrom ? { gte: new Date(`${query.dateFrom}T00:00:00.000Z`) } : {}), ...(query.dateTo ? { lte: new Date(`${query.dateTo}T23:59:59.999Z`) } : {}) };
  const homeownerSearch = q ? [{ homeowner: { id: { contains: q } } }, { homeowner: { block: { contains: q } } }, { homeowner: { lot: { contains: q } } }, { homeowner: { user: { name: { contains: q } } } }, { homeowner: { user: { email: { contains: q } } } }] : [];
  const requestWhere: Prisma.PaymentRequestWhereInput = { tenantId: admin.tenantId, ...(query.homeownerId ? { homeownerId: query.homeownerId } : {}), ...(query.status ? { status: query.status as never } : {}), ...(query.paymentType ? { type: query.paymentType as never } : {}), ...(query.collectionType ? { collectionType: query.collectionType as never } : {}), ...(Object.keys(dateRange).length ? { createdAt: dateRange } : {}), ...(q ? { OR: [{ id: { contains: q } }, { referenceNumber: { contains: q } }, { bill: { resolutionReference: { contains: q } } }, ...homeownerSearch] } : {}) };
  const paymentWhere: Prisma.PaymentWhereInput = { tenantId: admin.tenantId, status: "ACTIVE", ...(query.homeownerId ? { homeownerId: query.homeownerId } : {}), ...(query.method ? { method: query.method as never } : {}), ...(Object.keys(dateRange).length ? { paymentDate: dateRange } : {}), ...(q ? { OR: [{ id: { contains: q } }, { referenceNumber: { contains: q } }, { receiptNumber: { contains: q } }, { paymentCoverageDisplay: { contains: q } }, { bill: { resolutionReference: { contains: q } } }, ...homeownerSearch] } : {}) };
  const archiveWhere: Prisma.PaymentArchiveWhereInput = { tenantId: admin.tenantId, ...(query.homeownerId ? { homeownerId: query.homeownerId } : {}), ...(query.method ? { method: query.method as never } : {}), ...(Object.keys(dateRange).length ? { paymentDate: dateRange } : {}), ...(q ? { OR: [{ originalPaymentId: { contains: q } }, { referenceNumber: { contains: q } }, { receiptNumber: { contains: q } }, { paymentCoverageDisplay: { contains: q } }, { homeownerName: { contains: q } }, { property: { contains: q } }, { homeownerId: { contains: q } }] } : {}) };
  const paymentOrder: Prisma.PaymentOrderByWithRelationInput[] = query.sort === "oldest" ? [{ paymentDate: "asc" }, { createdAt: "asc" }] : query.sort === "amount_high" ? [{ amount: "desc" }] : [{ paymentDate: "desc" }, { createdAt: "desc" }];
  const [openBills, payments, paymentRequests, paymentArchives, requestCount, paymentCount, archiveCount, homeowners] = await Promise.all([
    prisma.bill.findMany({ where: { tenantId: admin.tenantId, balance: { gt: 0 }, archivedAt: null }, include: { homeowner: { include: { user: true } } }, orderBy: { dueDate: "asc" } }),
    prisma.payment.findMany({ where: paymentWhere, include: { homeowner: { include: { user: true } }, bill: true }, orderBy: paymentOrder, skip: (paymentPage - 1) * pageSize, take: pageSize }),
    prisma.paymentRequest.findMany({ where: requestWhere, include: { homeowner: { include: { user: true } }, bill: true, payment: true, collection: true }, orderBy: [{ status: "asc" }, { createdAt: "desc" }], skip: (requestPage - 1) * pageSize, take: pageSize }),
    prisma.paymentArchive.findMany({ where: archiveWhere, include: { voidedBy: true }, orderBy: { voidedAt: "desc" }, skip: (historyPage - 1) * pageSize, take: pageSize }),
    prisma.paymentRequest.count({ where: requestWhere }), prisma.payment.count({ where: paymentWhere }), prisma.paymentArchive.count({ where: archiveWhere }),
    prisma.homeownerProfile.findMany({ where: { tenantId: admin.tenantId, status: "ACTIVE" }, include: { user: true }, orderBy: { user: { name: "asc" } } }),
  ]);
  const billChoices = openBills.map((bill) => ({ id: bill.id, homeownerId: bill.homeownerId, homeowner: bill.homeowner.user.name, property: `Block ${bill.homeowner.block}, Lot ${bill.homeowner.lot}`, month: monthLabel(bill.billingMonth), billingMonth: bill.billingMonth.toISOString().slice(0, 10), balance: Number(bill.balance), balanceLabel: money(bill.balance), search: `${bill.homeowner.user.name} ${bill.homeowner.user.email} block ${bill.homeowner.block} lot ${bill.homeowner.lot} account ${bill.homeowner.id} ${bill.id} ${bill.resolutionReference ?? ""} ${monthLabel(bill.billingMonth)}`.toLowerCase() }));
  const preserved = Object.entries(query).filter(([key, value]) => value && !["requestPage", "paymentPage", "historyPage", "error", "success", "message"].includes(key)) as string[][];
  return <><PageHeader eyebrow="Collections" title="Payment tracking" description="Server-paginated GCash requests, active payments, approvals, validation, and read-only transaction history." />
    {query.error && <div className="mb-5 rounded-2xl border border-rose-200 bg-rose-50 p-4 text-sm font-bold text-rose-800">{query.error}</div>}{query.success && <div className="mb-5 rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-bold text-emerald-800">{query.message || "Payment transaction updated successfully."}</div>}
    <nav className="mb-4 flex gap-2 overflow-x-auto rounded-xl border border-slate-200 bg-white p-2 text-sm font-black shadow-sm">
      <a className="btn-secondary min-h-9 shrink-0 px-3 py-1.5" href="#record-payment">Record Payment</a>
      <a className="btn-secondary min-h-9 shrink-0 px-3 py-1.5" href="#payment-requests">Payment Requests</a>
      <a className="btn-secondary min-h-9 shrink-0 px-3 py-1.5" href="#active-payments">Active Payments</a>
      <a className="btn-secondary min-h-9 shrink-0 px-3 py-1.5" href="#transaction-history">Transaction History</a>
    </nav>
    <form className="card mb-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><input className="field" type="search" name="q" defaultValue={q} placeholder="OR, receipt, transaction, reference, homeowner" /><select className="field" name="homeownerId" defaultValue={query.homeownerId || ""}><option value="">All homeowners</option>{homeowners.map((item) => <option key={item.id} value={item.id}>{item.user.name} - B{item.block} L{item.lot}</option>)}</select><select className="field" name="status" defaultValue={query.status || ""}><option value="">All request statuses</option><option value="PENDING_REVIEW">Pending review</option><option value="APPROVED">Approved</option><option value="REJECTED">Rejected</option></select><select className="field" name="paymentType" defaultValue={query.paymentType || ""}><option value="">All payment types</option><option value="MONTHLY_DUES">Monthly dues</option><option value="OTHER_COLLECTION">Other collection</option></select><select className="field" name="collectionType" defaultValue={query.collectionType || ""}><option value="">All collection types</option>{["GATE_PASS","STICKER","MEMBERSHIP","CONSTRUCTION_BOND","CONTRACTOR_BOND","OTHER"].map((value) => <option key={value} value={value}>{value.replaceAll("_", " ")}</option>)}</select><select className="field" name="method" defaultValue={query.method || ""}><option value="">All payment methods</option>{["CASH","BANK_TRANSFER","GCASH","CHECK","OTHER"].map((value) => <option key={value}>{value.replaceAll("_", " ")}</option>)}</select><input className="field" type="date" name="dateFrom" defaultValue={query.dateFrom} aria-label="Date from" /><input className="field" type="date" name="dateTo" defaultValue={query.dateTo} aria-label="Date to" /><select className="field" name="sort" defaultValue={query.sort || "newest"}><option value="newest">Newest first</option><option value="oldest">Oldest first</option><option value="amount_high">Highest amount</option></select><div className="flex gap-2"><button className="btn-primary">Apply filters</button><Link className="btn-secondary" href="/admin/payments">Clear</Link></div></form>
    <section id="record-payment"><PaymentForm bills={billChoices} today={inputDate(new Date())} /></section>
    <section id="payment-requests" className="card mb-6 scroll-mt-24">
      <div className="mb-4"><h2 className="text-lg font-black">QR / GCash payment requests</h2><p className="text-sm text-slate-500">Review homeowner-submitted GCash references. Approval creates an official receipt and updates dues or other collections.</p></div>
      <div className="table-wrap shadow-none"><table className="data-table"><thead><tr><th>Homeowner</th><th>Purpose</th><th>Reference</th><th>Attachment</th><th>Status</th><th>Submitted</th><th className="text-right">Amount</th><th></th></tr></thead><tbody>
        {paymentRequests.map((request) => <tr key={request.id} data-search={`${request.homeowner.user.name} ${request.referenceNumber} ${request.status} ${request.collectionType ?? ""}`.toLowerCase()}><td><p className="font-bold">{request.homeowner.user.name}</p><p className="text-xs text-slate-400">B{request.homeowner.block} L{request.homeowner.lot}</p></td><td><p className="font-bold">{request.type === PaymentRequestType.MONTHLY_DUES ? `Monthly dues - ${request.bill ? monthLabel(request.bill.billingMonth) : "Bill"}` : collectionLabel(String(request.collectionType), request.description)}</p><p className="max-w-xs truncate text-xs text-slate-400">{request.payerNotes || request.reviewRemarks || "-"}</p></td><td><p className="font-mono text-xs">{request.referenceNumber}</p><Link className="mt-1 inline-flex items-center gap-1 text-xs font-bold text-pine-700" href={`/admin/payments/requests/${request.id}`}><Eye className="size-3" /> Details</Link></td><td>{request.proofImageUrl ? <span className="inline-flex items-center gap-1 rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-bold text-emerald-700"><Paperclip className="size-3" /> With Proof of Payment</span> : <span className="text-xs font-semibold text-slate-400">No Attachment</span>}</td><td><StatusBadge status={request.status} /></td><td>{shortDate(request.createdAt)}</td><td className="text-right font-black">{money(request.amount)}</td><td>{request.status === "PENDING_REVIEW" ? <div className="flex min-w-56 flex-col gap-2"><form action={approvePaymentRequestAction} className="space-y-2"><input type="hidden" name="id" value={request.id} /><input className="field min-h-9 py-1 text-xs" name="reviewRemarks" placeholder="Approval note optional" /><SubmitButton className="btn-primary w-full min-h-8 px-3 py-1 text-xs">Approve as paid</SubmitButton></form><form action={rejectPaymentRequestAction} className="space-y-2"><input type="hidden" name="id" value={request.id} /><input className="field min-h-9 py-1 text-xs" name="reviewRemarks" placeholder="Reason for rejection" /><SubmitButton className="btn-danger w-full min-h-8 px-3 py-1 text-xs">Reject</SubmitButton></form></div> : <div className="flex justify-end">{request.payment?.status === "ACTIVE" && <Link className="btn-secondary min-h-8 px-3 py-1" href={`/receipts/payment/${request.payment.id}`} target="_blank"><Printer className="size-4" /> Receipt</Link>}{request.collectionId && <Link className="btn-secondary min-h-8 px-3 py-1" href={`/receipts/collection/${request.collectionId}`} target="_blank"><Printer className="size-4" /> Receipt</Link>}</div>}</td></tr>)}
        {!paymentRequests.length && <tr><td colSpan={8} className="py-12 text-center text-slate-500">No QR payment requests yet.</td></tr>}
      </tbody></table></div>
    </section>
    <Pager page={requestPage} count={requestCount} pageSize={pageSize} pageKey="requestPage" preserved={preserved} />
    <section id="active-payments" className="mb-4 flex scroll-mt-24 flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="text-lg font-black">Active payment records</h2><p className="text-sm text-slate-500">Controlled amount updates are audited. Use Void to remove a transaction from active financial totals.</p></div><SearchInput placeholder="Search resident, reference or method" /></section>
    <div className="table-wrap"><table className="data-table"><thead><tr><th>Receipt / reference</th><th>Homeowner</th><th>Payment Coverage</th><th>Payment date</th><th>Method</th><th>Proof</th><th>Controlled amount update</th><th>Actions</th></tr></thead><tbody>
      {payments.map((payment) => <tr key={payment.id} data-search={`${payment.homeowner.user.name} ${payment.referenceNumber ?? ""} ${payment.method} ${paymentCoverageLabel(payment)}`.toLowerCase()}><td><p className="font-mono text-xs font-bold text-pine-700">{payment.receiptNumber || payment.id.slice(-8).toUpperCase()}</p><p className="font-mono text-[10px] text-slate-400">Ref: {payment.referenceNumber || "Not required"}</p></td><td className="font-bold">{payment.homeowner.user.name}</td><td className="font-bold">{paymentCoverageLabel(payment)}</td><td>{shortDate(payment.paymentDate)}</td><td>{payment.method.replaceAll("_", " ")}</td><td>{payment.proofUrl ? <a className="inline-flex items-center gap-1 text-xs font-bold text-pine-700" href={payment.proofUrl} target="_blank" rel="noreferrer"><Paperclip className="size-3" /> With Proof of Payment</a> : <span className="text-xs font-semibold text-slate-400">No Attachment</span>}</td><td><form action={updatePaymentAmountAction} className="grid min-w-64 gap-2 sm:grid-cols-[7rem_1fr_auto]"><input type="hidden" name="id" value={payment.id} /><label className="sr-only" htmlFor={`payment-amount-${payment.id}`}>Payment amount for {payment.homeowner.user.name}</label><input id={`payment-amount-${payment.id}`} className="field min-h-9 py-1 text-right font-black text-pine-700" name="amount" type="number" min="0.01" step="0.01" defaultValue={Number(payment.amount).toFixed(2)} required /><input className="field min-h-9 py-1 text-xs" name="reason" maxLength={500} placeholder="Update reason (optional)" /><SubmitButton className="btn-secondary min-h-9 px-3 py-1 text-xs"><Save className="size-3.5" /> Save</SubmitButton></form></td><td><div className="flex min-w-40 flex-col gap-2"><Link className="btn-secondary min-h-8 px-3 py-1" href={`/receipts/payment/${payment.id}`} target="_blank"><Printer className="size-4" /> Receipt</Link><PaymentVoidForm paymentId={payment.id} /></div></td></tr>)}
      {!payments.length && <tr><td colSpan={8} className="py-12 text-center text-slate-500">No payments recorded yet.</td></tr>}
    </tbody></table></div><Pager page={paymentPage} count={paymentCount} pageSize={pageSize} pageKey="paymentPage" preserved={preserved} />

    <section id="transaction-history" className="card mt-6 scroll-mt-24">
      <div className="mb-4 flex items-start gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-2xl bg-slate-100 text-slate-600"><History className="size-5" /></span><div><h2 className="text-lg font-black">Transaction history (read only)</h2><p className="text-sm text-slate-500">Voided transactions remain archived for audit/reference and are excluded from active payments, receipts, billing totals, and financial reports.</p></div></div>
      <div className="table-wrap shadow-none"><table className="data-table"><thead><tr><th>Original transaction</th><th>Payment Coverage / account</th><th>Homeowner</th><th>Payment details</th><th>Proof</th><th>Voided by</th><th>Reason</th></tr></thead><tbody>
        {paymentArchives.map((item) => <tr key={item.id}><td><p className="font-mono text-xs">{item.originalPaymentId}</p><p className="text-xs text-slate-400">Receipt {item.receiptNumber || "-"}</p></td><td><p className="font-bold">{paymentCoverageLabel(item)}</p><p className="text-xs text-slate-400">{item.property}</p></td><td>{item.homeownerName}</td><td><p className="font-black text-rose-700">{money(item.amount)}</p><p className="text-xs text-slate-500">{shortDate(item.paymentDate)} - {item.method.replaceAll("_", " ")}</p><p className="font-mono text-xs text-slate-400">{item.referenceNumber || "No reference required"}</p></td><td>{item.proofUrl ? <a className="inline-flex items-center gap-1 text-xs font-bold text-pine-700" href={item.proofUrl} target="_blank" rel="noreferrer"><Paperclip className="size-3" /> Archived proof</a> : <span className="text-xs text-slate-400">No attachment</span>}</td><td><p className="font-bold">{item.voidedBy.name}</p><p className="text-xs text-slate-400">{shortDate(item.voidedAt)}</p></td><td className="max-w-xs whitespace-pre-wrap text-sm">{item.voidReason || "No reason supplied."}</td></tr>)}
        {!paymentArchives.length && <tr><td colSpan={7} className="py-10 text-center text-slate-500">No voided payment transactions.</td></tr>}
      </tbody></table></div><Pager page={historyPage} count={archiveCount} pageSize={pageSize} pageKey="historyPage" preserved={preserved} />
    </section>
  </>;
}

function Pager({ page, count, pageSize, pageKey, preserved }: { page: number; count: number; pageSize: number; pageKey: string; preserved: string[][] }) { const pages = Math.max(1, Math.ceil(count / pageSize)); if (pages <= 1) return null; const url = (target: number) => { const params = new URLSearchParams(preserved); params.set(pageKey, String(target)); return `?${params}`; }; return <nav className="my-4 flex items-center justify-between gap-3 text-sm"><Link className={`btn-secondary ${page <= 1 ? "pointer-events-none opacity-50" : ""}`} href={url(page - 1)}>Previous</Link><span className="font-bold">Page {page} of {pages} | {count} records</span><Link className={`btn-secondary ${page >= pages ? "pointer-events-none opacity-50" : ""}`} href={url(page + 1)}>Next</Link></nav>; }
